CREATE TABLE `student` (
  `STD_ID` int(11) NOT NULL AUTO_INCREMENT,
  `STD_NUMBER` varchar(45) DEFAULT NULL,
  `STD_NAME` varchar(45) DEFAULT NULL,
  `STD_SURNAME` varchar(45) DEFAULT NULL,
  `STD_PHO` varchar(45) DEFAULT NULL,
  `STD_CITY` varchar(45) DEFAULT NULL,
  `STD_DISTICT` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`STD_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;